name: Ground
version: ${version}
main: kr.astar.ground.Ground
loader: kr.astar.ground.GroundLoader
api-version: '1.21'
authors: [ AS7AR ]
website: https://grassproject.github.io
dependencies:
  server:
    WorldGuard:
      required: true

permissions:
  astar.ground.*:
    default: op
    children:
      astar.ground.command:
        default: op
      astar.ground.purchase:
        default: op
      astar.ground.admin:
        default: op